service: user-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  stage: "dev"
  region: "ap-south-1"
  httpApi:
    cors: true

functions:
  signup:
    handler: app/handler.Signup
    events:
      - httpApi:
          path: /user/signup
          method: post
  login:
    handler: app/handler.Login
    events:
      - httpApi:
          path: /user/login
          method: post
  verify:
    handler: app/handler.Verify
    events:
      - httpApi:
          path: /user/verify
          method: post
      - httpApi:
          path: /user/verify
          method: get
  profile:
    handler: app/handler.Profile
    events:
      - httpApi:
          path: /user/profile
          method: post
      - httpApi:
          path: /user/profile
          method: put
      - httpApi:
          path: /user/profile
          method: get
  cart:
    handler: app/handler.Cart
    events:
      - httpApi:
          path: /user/cart
          method: post
      - httpApi:
          path: /user/cart
          method: put
      - httpApi:
          path: /user/cart
          method: get
  payment:
    handler: app/handler.Payment
    events:
      - httpApi:
          path: /user/payment
          method: post
      - httpApi:
          path: /user/payment
          method: put
      - httpApi:
          path: /user/payment
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript