service: user-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  stage: "dev"
  region: "ap-south-1"
  httpApi:
    cors: true
  environment:
    SNS_TOPIC: { Ref: CustomerTopic }
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resources:
        - !Ref CustomerTopic
custom:
  stage: "dev"
  serverless-offline:
    httpPort: 3001
    lambdaPort: 4000

functions:
  signup:
    handler: app/handler.Signup
    events:
      - httpApi:
          path: /signup
          method: post
  login:
    handler: app/handler.Login
    events:
      - httpApi:
          path: /login
          method: post
  verify:
    handler: app/handler.Verify
    events:
      - httpApi:
          path: /verify
          method: post
  get-verification-code:
    handler: app/handler.GetVerificationCode
    events:
      - httpApi:
          path: /verify
          method: get
  create-profile:
    handler: app/handler.CreateProfile
    events:
      - httpApi:
          path: /user
          method: post
  edit-profile:
    handler: app/handler.EditProfile
      - httpApi:
          path: /user
          method: put
  get-profile:
    handler: app/handler.GetProfile
      - httpApi:
          path: /user
          method: get
  create-cart:
    handler: app/handler.CreateCart
    timeout: 15
    events:
      - httpApi:
          path: /cart
          method: post
  delete-cart:
    handler: app/handler.DeleteCart
    timeout: 15
      - httpApi:
          path: /cart/{id}
          method: delete
  edit-cart:
    handler: app/handler.EditCart
    timeout: 15
      - httpApi:
          path: /cart/{id}
          method: put
  get-cart:
    handler: app/handler.GetCart
    timeout: 15
      - httpApi:
          path: /cart
          method: get
  collect-payment:
    handler: app/handler.CollectPayment
    timeout: 15
    events:
      - httpApi:
          path: /collect-payment
          method: post
  create-order:
    handler: app/handler.CreateOrder
    timeout: 15
    events:
      - httpApi:
          path: /order
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-optimize

resources:
  Resources:
    CustomerTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "customer sns topic description"
        TopicName: CustomerTopic
  Outputs:
    CustomerTopicInfo:
      Description: customer-topic
      value: !Ref CustomerTopic
      Export:
        Name: customer-topic
